# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS arch tf gf js trace work plug vt ar kind sdf ndr sdr pcp usd usdGeom usdVol usdMedia usdShade usdLux usdProc usdRender usdHydra usdRi usdSkel usdUI usdUtils usdPhysics garch hf hio cameraUtil pxOsd geomUtil glf hgi hgiGL hgiInterop hd hdar hdGp hdsi hdSt hdx usdImaging usdImagingGL usdProcImaging usdRiPxrImaging usdSkelImaging usdVolImaging usdAppUtils usdviewq)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target arch
add_library(arch SHARED IMPORTED)

set_target_properties(arch PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "Ws2_32.lib;Dbghelp.lib"
)

# Create imported target tf
add_library(tf SHARED IMPORTED)

set_target_properties(tf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/shirao/AppData/Local/Programs/Python/Python39/Include;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "Shlwapi.lib;Python3::Python;arch;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "C:/Users/shirao/AppData/Local/Programs/Python/Python39/Include;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target gf
add_library(gf SHARED IMPORTED)

set_target_properties(gf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "tf;arch"
)

# Create imported target js
add_library(js SHARED IMPORTED)

set_target_properties(js PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "tf"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target trace
add_library(trace SHARED IMPORTED)

set_target_properties(trace PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "tf;js;arch;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target work
add_library(work SHARED IMPORTED)

set_target_properties(work PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "tf;trace;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
)

# Create imported target plug
add_library(plug SHARED IMPORTED)

set_target_properties(plug PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "tf;arch;trace;work;js;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target vt
add_library(vt SHARED IMPORTED)

set_target_properties(vt PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "tf;trace;arch;gf;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target ar
add_library(ar SHARED IMPORTED)

set_target_properties(ar PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "js;tf;plug;arch;vt;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target kind
add_library(kind SHARED IMPORTED)

set_target_properties(kind PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "tf;plug"
)

# Create imported target sdf
add_library(sdf SHARED IMPORTED)

set_target_properties(sdf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "gf;tf;arch;trace;work;ar;vt;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target ndr
add_library(ndr SHARED IMPORTED)

set_target_properties(ndr PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "tf;sdf;plug;work;ar;vt;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target sdr
add_library(sdr SHARED IMPORTED)

set_target_properties(sdr PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "tf;sdf;ndr;ar;vt;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target pcp
add_library(pcp SHARED IMPORTED)

set_target_properties(pcp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "tf;sdf;trace;work;ar;vt;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target usd
add_library(usd SHARED IMPORTED)

set_target_properties(usd PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "pcp;tf;sdf;plug;arch;trace;work;kind;ar;vt;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target usdGeom
add_library(usdGeom SHARED IMPORTED)

set_target_properties(usdGeom PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "vt;usd;tf;sdf;plug;trace;work;js;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target usdVol
add_library(usdVol SHARED IMPORTED)

set_target_properties(usdVol PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "tf;usdGeom;usd"
)

# Create imported target usdMedia
add_library(usdMedia SHARED IMPORTED)

set_target_properties(usdMedia PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "usd;tf;usdGeom;sdf;vt"
)

# Create imported target usdShade
add_library(usdShade SHARED IMPORTED)

set_target_properties(usdShade PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "vt;usd;sdr;tf;usdGeom;sdf;ndr;js"
)

# Create imported target usdLux
add_library(usdLux SHARED IMPORTED)

set_target_properties(usdLux PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "usd;tf;usdGeom;sdf;ndr;vt;usdShade"
)

# Create imported target usdProc
add_library(usdProc SHARED IMPORTED)

set_target_properties(usdProc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "tf;usdGeom;usd"
)

# Create imported target usdRender
add_library(usdRender SHARED IMPORTED)

set_target_properties(usdRender PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "usd;gf;tf;usdGeom;usdShade"
)

# Create imported target usdHydra
add_library(usdHydra SHARED IMPORTED)

set_target_properties(usdHydra PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "tf;usd;usdShade"
)

# Create imported target usdRi
add_library(usdRi SHARED IMPORTED)

set_target_properties(usdRi PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "usd;tf;usdGeom;sdf;vt;usdShade;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target usdSkel
add_library(usdSkel SHARED IMPORTED)

set_target_properties(usdSkel PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "usd;gf;tf;usdGeom;sdf;arch;trace;work;vt;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target usdUI
add_library(usdUI SHARED IMPORTED)

set_target_properties(usdUI PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "tf;sdf;vt;usd"
)

# Create imported target usdUtils
add_library(usdUtils SHARED IMPORTED)

set_target_properties(usdUtils PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "usd;gf;tf;usdGeom;sdf;arch;usdShade;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target usdPhysics
add_library(usdPhysics SHARED IMPORTED)

set_target_properties(usdPhysics PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "usd;tf;usdGeom;sdf;plug;trace;work;vt;usdShade;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target garch
add_library(garch SHARED IMPORTED)

set_target_properties(garch PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "tf;opengl32;arch"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target hf
add_library(hf SHARED IMPORTED)

set_target_properties(hf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "tf;trace;plug"
)

# Create imported target hio
add_library(hio SHARED IMPORTED)

set_target_properties(hio PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "vt;hf;tf;plug;arch;trace;ar;js"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target cameraUtil
add_library(cameraUtil SHARED IMPORTED)

set_target_properties(cameraUtil PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "tf;gf"
)

# Create imported target pxOsd
add_library(pxOsd SHARED IMPORTED)

set_target_properties(pxOsd PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "tf;vt;gf;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/osdGPU.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/osdCPU.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/osdCPU.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/osdGPU.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
)

# Create imported target geomUtil
add_library(geomUtil SHARED IMPORTED)

set_target_properties(geomUtil PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "vt;gf;tf;arch;pxOsd"
)

# Create imported target glf
add_library(glf SHARED IMPORTED)

set_target_properties(glf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "hf;garch;hio;gf;tf;sdf;opengl32;plug;arch;trace;ar;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target hgi
add_library(hgi SHARED IMPORTED)

set_target_properties(hgi PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "tf;plug;gf"
)

# Create imported target hgiGL
add_library(hgiGL SHARED IMPORTED)

set_target_properties(hgiGL PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "garch;tf;arch;trace;hgi"
)

# Create imported target hgiInterop
add_library(hgiInterop SHARED IMPORTED)

set_target_properties(hgiInterop PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "garch;gf;tf;hgi;vt"
)

# Create imported target hd
add_library(hd SHARED IMPORTED)

set_target_properties(hd PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "vt;hf;cameraUtil;tf;sdf;plug;trace;work;pxOsd;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
)

# Create imported target hdar
add_library(hdar SHARED IMPORTED)

set_target_properties(hdar PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "ar;hd"
)

# Create imported target hdGp
add_library(hdGp SHARED IMPORTED)

set_target_properties(hdGp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "hf;hd;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
)

# Create imported target hdsi
add_library(hdsi SHARED IMPORTED)

set_target_properties(hdsi PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "vt;hf;hd;cameraUtil;tf;sdf;geomUtil;plug;trace;work;pxOsd"
)

# Create imported target hdSt
add_library(hdSt SHARED IMPORTED)

set_target_properties(hdSt PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "garch;hio;hd;sdr;tf;hdsi;hgiGL;trace;hgiInterop;glf;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/osdGPU.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/osdCPU.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/osdCPU.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/osdGPU.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
)

# Create imported target hdx
add_library(hdx SHARED IMPORTED)

set_target_properties(hdx PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "vt;garch;hdSt;hd;cameraUtil;gf;tf;sdf;plug;work;hgiInterop;glf;hgi;pxOsd"
)

# Create imported target usdImaging
add_library(usdImaging SHARED IMPORTED)

set_target_properties(usdImaging PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "gf;usdGeom;sdf;work;usdVol;usdShade;usdLux;hio;usd;tf;plug;hdar;pxOsd;hd;geomUtil;trace;usdRender;ar;vt;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
)

# Create imported target usdImagingGL
add_library(usdImagingGL SHARED IMPORTED)

set_target_properties(usdImagingGL PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/shirao/AppData/Local/Programs/Python/Python39/Include;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "gf;hdx;sdf;usdGeom;work;Python3::Python;usdShade;sdr;hdsi;garch;hio;usd;tf;plug;usdHydra;pxOsd;usdImaging;hd;trace;glf;ar;vt;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "C:/Users/shirao/AppData/Local/Programs/Python/Python39/Include;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
)

# Create imported target usdProcImaging
add_library(usdProcImaging SHARED IMPORTED)

set_target_properties(usdProcImaging PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "usdImaging;usdProc"
)

# Create imported target usdRiPxrImaging
add_library(usdRiPxrImaging SHARED IMPORTED)

set_target_properties(usdRiPxrImaging PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "vt;usdLux;hd;usd;gf;tf;usdGeom;sdf;plug;usdShade;trace;work;usdVol;ar;pxOsd;usdImaging;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/tbb_debug.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/tbb.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
)

# Create imported target usdSkelImaging
add_library(usdSkelImaging SHARED IMPORTED)

set_target_properties(usdSkelImaging PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "hio;hd;usdImaging;usdSkel"
)

# Create imported target usdVolImaging
add_library(usdVolImaging SHARED IMPORTED)

set_target_properties(usdVolImaging PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>"
  INTERFACE_LINK_LIBRARIES "usdImaging"
)

# Create imported target usdAppUtils
add_library(usdAppUtils SHARED IMPORTED)

set_target_properties(usdAppUtils PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "garch;hio;usd;gf;tf;usdGeom;sdf;usdImagingGL;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

# Create imported target usdviewq
add_library(usdviewq SHARED IMPORTED)

set_target_properties(usdviewq PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
  INTERFACE_LINK_LIBRARIES "tf;usdGeom;hd;usd;$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/lib/boost_python39-vc142-mt-gyd-x64-1_76.lib>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/lib/boost_python39-vc142-mt-x64-1_76.lib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<CONFIG:Debug>:S:/dist/pxr/OpenUSD-23.11/install/python39_d/include/boost-1_76>;$<$<CONFIG:Release>:S:/dist/pxr/OpenUSD-23.11/install/python39/include/boost-1_76>"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/openusdTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)